### ISSUE TITLE
Format dates strings

### ISSUE THREAD

**Issue by delete** [delete/kue-view#8]
All dates are showing as milliseconds. 
The dates should be formated to DD/MM/YYYY HH:mm:ss (24h).

Using this lib: https://date-fns.org/

**Comment by johnleoclaudio** [comment]
Let me try ;)

**Comment by johnleoclaudio** [comment]
Hmmm, I can't add tasks, I wonder why :/
https://www.useloom.com/share/585975255b714065906144d9c49d1896

**Comment by delete** [comment]
Thanks guys @johnleoclaudio @jvdub for the help! :smiley: 

My bad I didn't finish the readme with the whole "how to" thing. 
The **Kue View** UI loads the tasks from a Redis server.
I started this project to be an alternative to the UI from [this library](https://github.com/Automattic/kue#user-interface), because the main UI is kind of ugly and doesn't have some features that me and my team need (like select multiple tasks to restart or remove).

**Comment by delete** [comment]
Fix with #9 and https://github.com/delete/kue-view/commit/1c8d6e6fd10fd9909c017a1914d15c2e7d99215c
